# Generated by Django 4.0.3 on 2023-02-04 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupon', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coupon',
            name='user',
        ),
        migrations.AlterField(
            model_name='coupon',
            name='discount_amount',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='minimum_amount',
            field=models.FloatField(default=0),
        ),
    ]
