# Generated by Django 4.0.3 on 2023-02-04 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupon', '0003_alter_coupon_discount_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coupon',
            name='coupon_id',
        ),
        migrations.AddField(
            model_name='coupon',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
